<?php
// $Id: geshifilter.install,v 1.2.2.1 2007/12/12 14:48:27 soxofaan Exp $

/**
 * On uninstall: remove module variables and clear variable cache
 */
function geshifilter_uninstall() {
  db_query("DELETE FROM {variable} WHERE name LIKE 'geshifilter_%'");
  cache_clear_all('variables', 'cache');
}

/**
 * Implementation of hook_update_N()
 */
function geshifilter_update_1() {
  // clear the cache of available languages
  variable_del('geshifilter_available_languages');
  return array();
}
